version: '3.8'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: docker_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  flask:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  react:
    build: ./formulaire-react
    restart: always
    ports:
      - "3000:80"
